# Generated by Django 4.1.3 on 2022-11-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_color',
            new_name='variation_value',
        ),
    ]
